CREATE TABLE dealers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(120)             NOT NULL,
    address      VARCHAR(200)             NOT NULL,
    district     VARCHAR(120)             NOT NULL,
    rating       DECIMAL(2, 1)            NOT NULL,
    review_count INT                      NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120)             NOT NULL,
    email         VARCHAR(160)             NOT NULL,
    password_hash VARCHAR(100)             NOT NULL,
    role          VARCHAR(20)              NOT NULL,
    dealer_id     BIGINT REFERENCES dealers (id),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE vehicles (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   BIGINT                   NOT NULL REFERENCES users (id),
    plate      VARCHAR(7)               NOT NULL,
    model      VARCHAR(80)              NOT NULL,
    model_year INT                      NOT NULL,
    color      VARCHAR(40)              NOT NULL,
    mileage_km INT                      NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_vehicles_plate UNIQUE (plate)
);

CREATE TABLE vehicle_components (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id       BIGINT                   NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    type             VARCHAR(30)              NOT NULL,
    health           INT                      NOT NULL,
    health_last_week INT                      NOT NULL,
    detail           VARCHAR(200),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_vehicle_components_type UNIQUE (vehicle_id, type)
);

CREATE TABLE service_slots (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dealer_id BIGINT                   NOT NULL REFERENCES dealers (id) ON DELETE CASCADE,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    available BOOLEAN                  NOT NULL,
    version   BIGINT                   NOT NULL,
    CONSTRAINT uk_service_slots_start UNIQUE (dealer_id, starts_at)
);

CREATE TABLE bookings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT                   NOT NULL REFERENCES users (id),
    vehicle_id  BIGINT                   NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    slot_id     BIGINT                   NOT NULL REFERENCES service_slots (id),
    status      VARCHAR(20)              NOT NULL,
    total_cents BIGINT                   NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE news (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category     VARCHAR(20)              NOT NULL,
    title        VARCHAR(160)             NOT NULL,
    summary      VARCHAR(300)             NOT NULL,
    body         VARCHAR(4000)            NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_vehicles_owner ON vehicles (owner_id);
CREATE INDEX ix_service_slots_dealer ON service_slots (dealer_id, starts_at);
CREATE INDEX ix_bookings_customer ON bookings (customer_id);
CREATE INDEX ix_bookings_slot ON bookings (slot_id);
